### PR TITLE
Fix Undefined Bug from Admin console

### LINKED ISSUE #14: [BUG] Error and infinite load on Papertrail widget when using PostgreSQL and there are no Trails to show
```
[2024-02-01 14:10:31.281] error: select "t0".*, "t0"."id", "t0"."created_by_id", "t0"."updated_by_id" from "public"."plugin_paper_trail_trails" as "t0" where ((("t0"."content_type" = $1 and "t0"."record_id" = $2))) order by "t0"."version" DESC limit $3 - invalid input syntax for type bigint: "undefined"
error: select "t0".*, "t0"."id", "t0"."created_by_id", "t0"."updated_by_id" from "public"."plugin_paper_trail_trails" as "t0" where ((("t0"."content_type" = $1 and "t0"."record_id" = $2))) order by "t0"."version" DESC limit $3 - invalid input syntax for type bigint: "undefined"
    at Parser.parseErrorMessage (/Users/darrylwalker/dd-api/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/Users/darrylwalker/dd-api/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/darrylwalker/dd-api/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/Users/darrylwalker/dd-api/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:514:28)
    at Socket.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:545:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:495:3)
    at Readable.push (node:internal/streams/readable:375:5)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```
Screenshot 2024-02-01 at 14 10 53

### PR DESCRIPTION
**Pull request by redondi88**
fix #14 and removed issue on disabled collections

### CODE REVIEW

**Comment by PenguinOfWar** [comment]
Thanks @redondi88, I'll get this tested and released as 0.4.1.

**Review by PenguinOfWar — APPROVED** [review]

**Comment by redondi88** [comment]
Awesome! thanks.
Would this create a new release? id like to push this to the clients.

**Comment by PenguinOfWar** [comment]
You can grab it from 0.4.1 on npm. Have pushed the release!

There is a further small UI refinement I would like to make, I’ll get it out in a couple of days as 0.4.2. 

Thanks again for the fix!

**Comment by PenguinOfWar** [comment]
@redondi88 small UI refinement out in v0.4.2. Let me know if you have any issues.

Thanks for using Paper Trail!

**Pull request merged**
